### ISSUE TITLE
Weekly structure organization

### ISSUE THREAD

**Issue by tuteng** [streamnative/pulsar_weekly#3]
I suggest using the following structure to organize the content of weekly.

--2019
----2019-10
------2019-10-23-pulsar-weekly.md
------2019-10-18-pulsar-weekly.md
------2019-10-05-pulsar-weekly.md
----2019-09
------2019-09-05-pulsar-weekly.md
------2019-09-13-pulsar-weekly.md
--2018
----2018-12
------2018-12-23-pulsar-weekly.md
------2018-12-18-pulsar-weekly.md
------2018-12-05-pulsar-weekly.md
----2018-11
------2018-11-05-pulsar-weekly.md
------2018-11-13-pulsar-weekly.md

**Comment by sijie** [comment]
+1 LGTM

**Comment by sijie** [comment]
@tuteng can you send out a pull request to refactor the structure?
